### PR TITLE
release v0.4.1

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by marten-seemann** [comment]
> required module github.com/microcosm-cc/bluemonday@v1.0.1 retracted by module author: Retract older versions as only latest is to be depended upon

That's not what retractions are supposed to be used for. But we should probably update the dependency anyway, otherwise this warning will bubble up the stack.

**Comment by dirkmc** [comment]
@marten-seemann anything I can help out with here to get this release over the line?

**Comment by marten-seemann** [comment]
@dirkmc Would be great if you could investigate what's going on with the dependency (probably just needs updating), and then create a new PR to cut a release.

**Comment by BigLep** [comment]
Close because 0.5 was released

**Pull request closed without merging**
